logging:
  version: 1
  formatters:
    simpleFormatter:
      format: " [%(asctime)s] - %(name)s - %(levelname)s - %(message)s"
  handlers:
    consoleHandler:
      class: logging.StreamHandler
      level: INFO
      formatter: simpleFormatter
      stream: ext://sys.stdout
    fileHandler:
      class: logging.handlers.TimedRotatingFileHandler
      level: DEBUG
      filename: logs1.log
      when: midnight
      interval: 1
      backupCount: 30
      formatter: simpleFormatter
  loggers:
    myLogger:
      level: DEBUG
      handlers: [consoleHandler, fileHandler]
      propagate: no
  root:
    level: DEBUG
    handlers: [consoleHandler, fileHandler]